version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - ${PORT_MONGO}:${PORT_MONGO_DOCKER}
    volumes:
      - mongodb:/data/db

  app:
    container_name: "api-rest-ts"
    restart: always
    depends_on:
      - mongo
    build: 
      context: .
    ports:
      - ${PORT}:${DOCKER_PORT}
    links:
      - mongo
    volumes:
      - .:/home/Api-Rest-TypeScript
volumes:
  mongodb: