version: '3.9'

services:
  mongo:
    image: grover101/mongo-alpine
    restart: always
    ports:
      - ${PORT_MONGO}:${PORT_MONGO_DOCKER}
    volumes:
      - ./mongodb:/data/db
      - ./mongodb_config:/data/configdb

  app:
    container_name: "api-rest-ts"
    restart: always
    depends_on:
      - mongo
    build: 
      context: .
    ports:
      - ${PORT}:${DOCKER_PORT}
    links:
      - mongo
    volumes:
      - .:/home/app
volumes:
  mongodb: